package lsm

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

// This file answers, by observation, the question `leash doctor` could until now
// only guess at: will leash's eBPF LSM programs actually load and attach on this
// kernel? Reading "bpf" out of /sys/kernel/security/lsm (runner.ProbeBPFLSM) is
// a cheap proxy for that, and a kernel can list bpf and still refuse the
// programs — the verifier can reject bpf_d_path, BTF can be absent, ring buffer
// creation can fail, or a program can exceed the instruction limit (leash's own
// hard-link guard hit that ceiling in issue #29).
//
// It lives in package lsm rather than in doctor because the loader it must use
// (loadLsmOpen, generated by bpf2go for linux and stubbed for everything else)
// is unexported. That is the point: the probe judges the *shipped* programs. A
// synthetic program that verifies while the real ones do not is the exact
// failure mode this replaces.

// attachProbeTimeout bounds the whole probe. Loading and verifying a program is
// normally milliseconds; the bound exists so a pathological kernel cannot turn a
// readiness command into a hang. Exceeding it degrades to unknown, never to an
// error.
const attachProbeTimeout = 10 * time.Second

// attachProbeProgram is the representative program. One is enough to establish
// attachability, and lsm_open is the right one: it is a *required* program of
// leash's file-open module, and it is the program that uses bpf_d_path and the
// ring buffer, so verifying it exercises the helpers issue #23 named.
const attachProbeProgram = "lsm_open"

// attachProbeOptionalPrograms mirrors OpenLsm.LoadAndAttach's
// BPFConfig.OptionalProgramNames. It has to, or the probe would disagree with
// the loader it is supposed to be reporting on: a real run whose optional
// hard-link guard fails verification drops that one hook and keeps enforcing,
// so a probe that called the whole kernel unattachable there would report a
// working host as broken.
var attachProbeOptionalPrograms = []string{"lsm_link"}

// AttachState is the tri-state answer to "can leash's eBPF LSM programs attach
// on this kernel?", deliberately shaped like runner.LSMState so the two read
// consistently in the same JSON document.
//
// The zero value is AttachUnknown, so a value that was never filled in cannot
// claim an observation that did not happen. The ordering is not meaningful —
// compare against the constants.
type AttachState int

const (
	// AttachUnknown means the probe could not run or could not reach a verdict.
	// An unprivileged process lands here (loading a BPF_PROG_TYPE_LSM program
	// needs CAP_BPF), and so does any non-Linux build. It is never a claim
	// about the kernel.
	AttachUnknown AttachState = iota
	// AttachUnattachable means the kernel was asked and said no: the verifier
	// rejected the programs, or the attach itself was refused.
	AttachUnattachable
	// AttachAttachable means the programs verified, attached, and were detached
	// again. This is the only state that reports an observation of success.
	AttachAttachable
)

// String is the wire form used by `leash doctor --json`.
func (s AttachState) String() string {
	switch s {
	case AttachAttachable:
		return "attachable"
	case AttachUnattachable:
		return "unattachable"
	default:
		return "unknown"
	}
}

// MarshalJSON emits the string form, matching LSMState: an integer would make
// the payload's meaning depend on a constant table the consumer does not have.
func (s AttachState) MarshalJSON() ([]byte, error) { return json.Marshal(s.String()) }

// UnmarshalJSON is the exact inverse, so a Go consumer can decode a document
// this package's states appear in. Without the pair, every value would decode
// to the zero state whatever the document said. An unrecognised word errors
// rather than falling back to unknown: a state this build does not know is not
// one it may reinterpret.
func (s *AttachState) UnmarshalJSON(data []byte) error {
	var word string
	if err := json.Unmarshal(data, &word); err != nil {
		return fmt.Errorf("attach state must be a JSON string: %w", err)
	}
	switch word {
	case "attachable":
		*s = AttachAttachable
	case "unattachable":
		*s = AttachUnattachable
	case "unknown":
		*s = AttachUnknown
	default:
		return fmt.Errorf("unknown attach state %q (want attachable, unattachable or unknown)", word)
	}
	return nil
}

// AttachStage names the step that produced the verdict. It exists because a
// verifier rejection and an attach rejection call for completely different
// remedies — the first means this kernel cannot run leash's programs at all
// (BTF, bpf_d_path, the instruction limit), the second means the programs are
// fine and the kernel is not configured to accept BPF LSM attachments.
type AttachStage string

const (
	// AttachStageNone is the stage of a verdict no single step produced: a
	// clean success, a timeout, or a panic.
	AttachStageNone AttachStage = ""
	// AttachStageSkipped means the probe was deliberately not attempted (the
	// caller asked not to, or the process could not have run it).
	AttachStageSkipped AttachStage = "skipped"
	// AttachStageLoad means the embedded program spec could not even be read —
	// on a non-Linux build, this is the stub loader.
	AttachStageLoad AttachStage = "load"
	// AttachStageVerify means ebpf.NewCollection failed: the kernel's verifier
	// judged the programs.
	AttachStageVerify AttachStage = "verify"
	// AttachStageAttach means the programs verified but link.AttachLSM failed.
	AttachStageAttach AttachStage = "attach"
)

// AttachProbe is one probe's result: the verdict, the step that produced it,
// and the kernel's own words. Detail is the actionable part of an
// unattachable verdict and must be preserved verbatim rather than summarised;
// for an unknown verdict it says why no verdict was reached.
type AttachProbe struct {
	State  AttachState
	Stage  AttachStage
	Detail string
}

// SkippedAttachProbe builds the unknown result for a probe that was never
// attempted, so callers that gate on privilege or on a flag report the same
// shape as one that ran. reason is folded into Detail verbatim.
func SkippedAttachProbe(reason string) AttachProbe {
	return AttachProbe{State: AttachUnknown, Stage: AttachStageSkipped, Detail: reason}
}

// ProbeAttachable loads leash's real LSM programs, lets the kernel verify them,
// attaches the representative one, and detaches it again — then reports what
// happened. It is the exported seam for `leash doctor` (internal/doctor).
//
// It never returns an error and never panics: a probe that cannot reach a
// verdict reports AttachUnknown with the reason, because a readiness command
// that fails on its own diagnostic is worse than the guess it replaces.
//
// It is safe to run on a host where leash is already enforcing. The collection
// is independent (fresh maps, nothing pinned, nothing shared with a running
// leash) and the one link is closed before this returns. While it is attached,
// the program is inert: lsm_open's first act is is_target_cgroup(), which reads
// target_cgroup[0] — zero in a fresh collection — and returns 0 (allow) for
// every file open. Nothing existing is detached, replaced or enumerated.
func ProbeAttachable() AttachProbe {
	return probeAttachableWithin(attachProbeTimeout, runAttachProbe)
}

// probeAttachableWithin is ProbeAttachable with the bound and the probe body
// injected, so the fail-soft branches (a probe that hangs, a probe that panics)
// can be tested for real instead of asserted about.
func probeAttachableWithin(bound time.Duration, probe func() AttachProbe) AttachProbe {
	// Buffered: if the probe finishes after the bound has expired, the send
	// must not block a goroutine forever. The late goroutine still runs its own
	// deferred Close calls, so nothing is leaked by giving up on it.
	done := make(chan AttachProbe, 1)
	go func() { done <- attachProbeGuarded(probe) }()

	timer := time.NewTimer(bound)
	defer timer.Stop()
	select {
	case result := <-done:
		return result
	case <-timer.C:
		return AttachProbe{
			State:  AttachUnknown,
			Stage:  AttachStageNone,
			Detail: fmt.Sprintf("the attachability probe did not finish within %s", bound),
		}
	}
}

// attachProbeGuarded is the panic boundary. A panic from deep in the loader or
// the ebpf library must degrade this one signal to unknown, not take down a
// command whose entire job is to still produce a report.
func attachProbeGuarded(probe func() AttachProbe) (result AttachProbe) {
	defer func() {
		if r := recover(); r != nil {
			result = AttachProbe{
				State:  AttachUnknown,
				Stage:  AttachStageNone,
				Detail: fmt.Sprintf("the attachability probe panicked and was contained: %v", r),
			}
		}
	}()
	return probe()
}

// runAttachProbe is the probe proper. Every resource it opens is released by a
// defer, on every path including the error ones, so repeated runs cannot grow
// the process's descriptor table.
func runAttachProbe() AttachProbe {
	// The same rlimit the real load path raises (leashd calls this immediately
	// before LoadAndAttach). Without it the probe could be refused for a reason
	// leash itself would never hit, which is precisely the drift this probe
	// exists to remove. It only widens a limit of this short-lived process.
	_ = BumpMemlockRlimit()

	spec, err := loadLsmOpen()
	if err != nil {
		// Includes the non-Linux stub loader: no spec, so nothing was observed.
		return AttachProbe{State: AttachUnknown, Stage: AttachStageLoad, Detail: err.Error()}
	}

	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		// Mirrors LoadAndAttachBPFWithSetup: NewCollection verifies EVERY
		// program eagerly, so an optional best-effort hook that the verifier
		// rejects would otherwise sink the whole collection — and the real run
		// survives exactly that by reloading without the optional programs.
		if fresh, freshErr := loadLsmOpen(); freshErr == nil {
			for _, name := range attachProbeOptionalPrograms {
				delete(fresh.Programs, name)
			}
			if stripped, strippedErr := ebpf.NewCollection(fresh); strippedErr == nil {
				coll, err = stripped, nil
			}
		}
	}
	if err != nil {
		// EPERM/EACCES is not a judgement on the kernel, it is a judgement on
		// this process. Reporting "unattachable" here would be the fabricated
		// verdict doctor exists to prevent.
		if isProbePermissionError(err) {
			return AttachProbe{State: AttachUnknown, Stage: AttachStageVerify, Detail: privilegeDetail(err)}
		}
		// One call covers bpf_d_path, the ring buffer, BTF and the verifier's
		// instruction limit, so the kernel's text is the whole diagnosis.
		return AttachProbe{State: AttachUnattachable, Stage: AttachStageVerify, Detail: err.Error()}
	}
	defer coll.Close()

	prog := coll.Programs[attachProbeProgram]
	if prog == nil {
		return AttachProbe{
			State:  AttachUnknown,
			Stage:  AttachStageLoad,
			Detail: fmt.Sprintf("the representative program %q is not in the loaded collection", attachProbeProgram),
		}
	}

	// Verification alone is not the question. The commonest real failure is a
	// program that verifies cleanly on a kernel where "bpf" is not an active
	// LSM, so only the attach discovers it.
	lnk, err := link.AttachLSM(link.LSMOptions{Program: prog})
	if err != nil {
		if isProbePermissionError(err) {
			return AttachProbe{State: AttachUnknown, Stage: AttachStageAttach, Detail: privilegeDetail(err)}
		}
		return AttachProbe{State: AttachUnattachable, Stage: AttachStageAttach, Detail: err.Error()}
	}
	// Detached on return, which is the next statement: leash is a sandbox, not
	// a squatter, and doctor must leave the kernel exactly as it found it.
	defer lnk.Close()

	return AttachProbe{State: AttachAttachable, Stage: AttachStageNone}
}

// isProbePermissionError reports whether err is the kernel refusing *this
// process* rather than refusing leash's programs. Getting this wrong in the
// other direction is the failure CAP-2 names: an unprivileged run must never
// report a kernel as unattachable.
func isProbePermissionError(err error) bool {
	if err == nil {
		return false
	}
	// syscall.EPERM/EACCES and golang.org/x/sys/unix.EPERM/EACCES are the same
	// syscall.Errno values, so matching the syscall constants matches both.
	if errors.Is(err, syscall.EPERM) || errors.Is(err, syscall.EACCES) ||
		errors.Is(err, os.ErrPermission) || os.IsPermission(err) {
		return true
	}
	// Fallback for a library that renders the errno into its message without
	// wrapping it. Erring toward "unknown" is the safe direction: the cost of a
	// false positive is a signal we decline to report, the cost of a false
	// negative is a fabricated verdict.
	lowered := strings.ToLower(err.Error())
	return strings.Contains(lowered, "operation not permitted") ||
		strings.Contains(lowered, "permission denied")
}

// privilegeDetail names the missing privilege alongside the kernel's own text,
// so the reader is not left to infer why "operation not permitted" happened.
func privilegeDetail(err error) string {
	return fmt.Sprintf("this process may not load BPF LSM programs (CAP_BPF, or root), so attachability was not established: %v", err)
}
